server:
  port: 48080

spring:
  datasource:
    url: jdbc:mariadb://192.168.50.13:3306/ERR209_TES
    username: error209
    password: p@ssw0rd
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      # ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  # Ollama AI
  ai:
    ollama:
      base-url: http://192.168.50.13:11434
      chat:
        options:
          model: iapp/chinda-qwen3-4b
          temperature: 0.7

  modelfile:
    modelfilepath: "./modelfile"
    modelname: "springcoreai"

  application:
    upload:
      path: uploads

# 5. JWT Configuration
jwt:
  secret: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXk=  # Base64 encoded key
  access-expiration-in-ms: 3600000   # 1 Minute
  refresh-expiration-in-ms: 86400000  # 24 Hour

logging:
  level:
    org.hibernate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
